### ISSUE TITLE
Android-x86 integration

### ISSUE THREAD

**Issue by dadreamer** [flomio/flomio_android#8]
Hi!

Is it possible to integrate your NFC driver/service into Android-x86 build to get it working "out-of-box" for any other applications? I mean some kind of replacement of native NFC stack with your own stack. I'd like to use an external NFC reader in VirtualBox guest with Android-x86. Are there any instructions for how could I make a new build along with your service? I also need HCE functionality, if your SDK offers it.

**Comment by scottire** [comment]
We have a cross platform JavaScript SDK that we have given customers who require android support. 
You would need cordova wrapper for Android-x86. You would need to purchase some Flomio Service Hours to get support for this because our team is very stretched and there is not a demand for this from other customers.
Flomio Service Hours info:
https://flomio.com/shop/apps/flomio-service-instantly-support-your-needs/

**Comment by dadreamer** [comment]
Thank you for the reply, Scott. I have some questions about the details.
- I see that you use the vendor supplied Java libraries to have your SDK working (ACS, Feitian) and there's no need for the drivers as the readers are PC/SC standard readers. And Cordova is used just for a cross-platform compatibility. But in order to get this working under Android-x86 it's needed to rewrite its native NFC libraries (_nfcnci_ and others) or make some wrapper, translating commands between your apps/libraries and underlying OS layer (I assume some C/C++ work here). Is that possible at all to alter and connect all the things together?
- Is Cordova Android plugin finished or is it still at pre/alpha? [This](https://github.com/flomio/cordova-plugin-flomio/issues/25) thread makes me think, that it's still a work in progress.
- Have you seen [External NFC Service API](https://github.com/skjolber/external-nfc-api) by Thomas Skjølberg? Back in the days he did a great work by making some tools to support ACS readers on Android (e.g., a system service and API to interact with it from the user apps). Might it be possible to reuse his works for Android-x86 somehow?..
- Is $450 for the whole project to be done or just for "touching the water" (possible or not)? How many service hours does this payment give to me? Do I need to pay for Cordova plugin to be written first and then pay for Android-x86 integration?

**Comment by sublimator** [comment]
@dadreamer 

We are using a fully custom JS SDK which connects to the reader via bluetooth (handling authentication/encryption etc). 

Note that the SDK is only really suitable for cordova/ionic applications.
It's unlikely that you'll be able to share the host's BLE with the android-x86 guest. 

Let us know if you're still interested. 

I don't think ACS supply any compatible USB drivers for you to use with the external service API you linked. I've seen Thomas's work previously and it indeed looked pretty great! Maybe you could contact him to see if he has any ideas?

**Comment by dadreamer** [comment]
@sublimator 
> via bluetooth

There's also ACR122U reader in the shop, which is wire-based, so has to work using common USB drivers and PC/SC standard ones. Does your SDK support USB readers?

> It's unlikely that you'll be able to share the host's BLE with the android-x86 guest.

Well, I could pass-through an USB device from the host to the guest (flash disk, smartphone, NFC reader or Bluetooth dongle). But I have never tested the last one, so I need to check it out. I will report if it works as it should.

> I don't think ACS supply any compatible USB drivers for you to use with the external service API you linked.

As it appears, the service doesn't need any extra drivers, because the reader utilizes standard drivers of the Android OS. I had a bunch of tests with [External NFC Reader Service](https://play.google.com/store/apps/details?id=com.skjolberg.nfc.external&hl=ru) and External NFC client app and they both work just fine on a clean Android-x86 install.

> Maybe you could contact him to see if he has any ideas?

I did that already. He said that it would be possible to alter his service in some ways to get it working instead of Android-x86 native one, but ATM he's busy in other projects, so not going to waste the time for this one.

**Comment by sublimator** [comment]
Ok, good luck then!

We don't have any usb sdks for android
